#heading(
  level: 1,
  numbering: none,
)[Conclusion]
// ~1 page

Ce rapport sur la gestion du portefeuille projets de l’entreprise Kelbrion nous a permis de mettre en lumière les atouts d’une cellule PMO et de l’harmonisation de la gestion de projets au sein d’une entreprise.

Nous avons d’abord proposé, dans la partie @referentiel-pmo[] Référentiel PMO, une méthode applicable à chaque projet, organisée en 9 rubriques, et nous avons produit des modèles de documents réutilisables (D1 à D11) pour faire gagner du temps aux chefs de projet, qui sont responsables de la bonne tenue des registres.

Nous avons ensuite détaillé, dans la partie @priorisation-portefeuille[] Priorisation du portefeuille, une méthode de cotation des projets, qui couvre à la fois l’aspect économique (budget prévisionnel et rentabilité attendue, partie 2.@calcul-de-la-rentabilite[] Calcul de la rentabilité), la répartition dans le temps (priorités, dépendances, projets bloquants) et l’alignement avec la stratégie de l’entreprise (partie 2.@arbitrage-strategique[] Arbitrage stratégique).

Nous avons appliqué cette méthode aux 10 projets de la DSI Kelbrion liés à l’ouverture d’un nouveau site de production. Le classement des projets selon chacun de ces critères (partie 2.@cotation-projets[] Cotation des projets) nous a éclairés sur les dates de lancement et les éventuels choix à opérer (P4 indispensable pour l’ouverture, P10 le moins urgent et le moins bloquant, P7 et P9 également décalables si besoin). L’analyse du portefeuille nous a également montré que la période de janvier à juillet 2027 serait très chargée pour les développeurs de l’entreprise, et qu’il faudra manifestement faire appel à des prestataires extérieurs, ce qui a été pris en compte dans le chiffrage des projets. Néanmoins, l’enveloppe de 2 000 000 € est elle aussi apparue comme limitée compte tenu du nombre et de l’ampleur des projets : avec une provision de 5 % par projet, le portefeuille la dépasse déjà de 2,8 %. Dans ce contexte, le portefeuille nous semble maîtrisable, mais la marge de manœuvre demeure étroite, et les budgets prévisionnels sont sous pression, avec seulement 5 % de marge de manœuvre (provision pour risques).

Nous avons ensuite choisi d’analyser plus finement le projet P4 « Déploiement d’un MES », car c’est à la fois l’un des projets les plus alignés avec la stratégie de l’entreprise (3,7/5), mais aussi clairement le projet le plus rentable (111,5 % de retour sur investissement sur 3 ans), et qu’en plus de cela il est bloquant pour l’ouverture, car c’est lui qui permettra d’envoyer les ordres de fabrication aux machines. C’est certes un projet SI, mais surtout un projet au cœur de l’activité économique de l’entreprise : il génère de la valeur. De plus, son périmètre est complet puisqu’il fait intervenir à la fois des développeurs, des administrateurs système, des fournisseurs extérieurs pour un logiciel et du matériel, et des métiers de l’entreprise (du service Production).

Nous avons appliqué la méthode exposée dans la partie @referentiel-pmo[] Référentiel PMO au projet P4 (partie @gestion-projet-p4[] Gestion du projet), et cela nous a permis d’aller dans le détail de son périmètre, de ses fonctionnalités attendues, de son planning et de son budget prévisionnels, de ses risques et de sa gouvernance. L’analyse AMDEC a notamment fait ressortir la complexité de l’interface entre le MES et l’ERP (R01) comme le risque le plus critique du projet (partie 3.@gestion-risques[] Gestion des risques). Il s’agissait de l’étape préliminaire avant de pouvoir simuler le pilotage de ce projet dans le temps, ce que nous avons fait dans la partie @pilotage-tdb[] Pilotage et tableau de bord, à travers 4 scénarios dynamiques qui alimentent le tableau de bord projet (partie 4.@tableau-de-bord[] Tableau de bord).

L’étude de ces scénarios a été particulièrement éclairante, car elle nous a permis de mettre en lumière certaines lacunes qui n’avaient pas été anticipées durant la phase de rédaction des documents du référentiel : un profil de développeurs partagé entre 4 projets et planifié sans marge, un avancement uniquement déclaratif, ou encore l’absence de procédure de retour arrière des interfaces, qui provoque l’échec de la bascule dans le scénario de tensions.

Après la phase de clôture, dans laquelle nous avons présenté le plan de recette et le PV de recette (partie @recette-cloture[] Recette et clôture), nous avons proposé une boucle d’amélioration (partie 6.@boucle-amelioration[] Boucle d’amélioration continue) qui s’appuie sur la rédaction de retours d’expérience (partie 6.@retour-experience[] Retour d’expérience). Fait étonnant, sans même avoir réellement piloté le projet, les scénarios étudiés nous ont d’ores et déjà permis d’émettre des recommandations, comme le fait de débuter le choix du fournisseur MES le plus tôt possible ou encore d’adapter la provision pour risques à la maîtrise des risques mesurée pour chaque projet, alors que la provision de 5 % est dépassée dans les scénarios défavorable et de tensions.

Aujourd’hui, l’entreprise Kelbrion dispose d’une méthode PMO claire et utile pour gérer à la fois un portefeuille dans sa globalité, et un projet avec une vision et un pilotage plus précis.

Si nous devions rejouer l’un des 4 scénarios d’évolution du projet P4 sans avoir mis en place une gestion de projet avec des responsabilités bien définies, des seuils d’alerte identifiés, des réunions planifiées et des risques anticipés, aucune trajectoire ne serait en mesure de respecter les délais et les attentes (pas même le scénario « favorable »). C’est certainement l’enseignement le plus important de ce dossier.
